### ISSUE TITLE
Missing daggers on the warrior sim for classic vanilla

### ISSUE THREAD

**Issue by suzumiya999** [wowsims/classic#55]
all daggers seem to be missing from warrior sim

https://www.wowhead.com/classic/item=18805/core-hound-tooth
https://www.wowhead.com/classic/item=18816/perditions-blade
https://www.wowhead.com/classic/item=228757/felstriker

if you could please add daggers to war sim when you get a chance. thanks, glad the best sim is back

**Comment by TheBackstabi** [comment]
Daggers are present on the Warrior UI. Double check your filters, you may have them disabled.

![image](https://github.com/user-attachments/assets/e14ce66f-dc1a-41e5-937e-c5ef40adf69d)
![image](https://github.com/user-attachments/assets/927dee37-fd08-4e61-898b-544a72a1e386)
